# Generated by Django 4.2 on 2023-09-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_article_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
