# Generated by Django 4.2 on 2023-07-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stay_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
