# Generated by Django 4.2.3 on 2024-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_article_stay_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
